name = "wallwidgy"
main = ".open-next/worker.js"
compatibility_date = "2025-05-28"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "wallwidgy-db"
database_id = "c29dd30b-06a5-42b3-82e0-3ad67ff4b5f9"

