name = "wallwidgy"
main = ".open-next/worker/index.mjs"
compatibility_date = "2025-05-28"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = false
invocation_logs = true

